default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV.fetch('DB_PASS', 'sekret') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

development:
  <<: *default
  database: todo_app_intellimizers_development

test:
  <<: *default
  database: todo_app_intellimizers_test

production:
  <<: *default
  database: todo_app_intellimizers_production
  username: ledgerdary
  password: <%= ENV["lEDGERDARY_DATABASE_PASSWORD"] %>
