#!/bin/bash

docker-compose > /dev/null 2>&1
if [ "$?" = "127" ] ; then
  shopt -s expand_aliases
  alias docker-compose="docker compose"
fi

if [ -n "$(docker ps -f name=todo_app_intellimizers | grep -w 'Up' | awk '{print $NF}')" ]; then
  echo "Re-Using Existing Container..."
  CMD="docker exec -it todo_app_intellimizers bash -c '$@'"
else
  echo "Creating New Container..."
  CMD="docker-compose run --name todo_app_intellimizers_tmp --rm todo_app_intellimizers bash -c 'bundle install && bundle exec rails db:setup && $@'"
fi
echo $CMD
eval $CMD
